-- SOFTEN PERFORMANCE HUB V2.29.9
-- Instalador cumulativo para um projeto Supabase NOVO.
-- Para uma base existente, utilize somente as migrações pendentes em supabase/migrations/.
-- Gerado a partir do schema base e das migrações oficiais do projeto.

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.squads (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  code text not null,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (organization_id, code)
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  squad_id uuid references public.squads(id) on delete set null,
  full_name text not null,
  email text,
  role text not null check (role in ('super_admin','squad_admin','technician')),
  technician_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (role <> 'technician' or (squad_id is not null and technician_name is not null)),
  check (role <> 'squad_admin' or squad_id is not null)
);

-- Compatibilidade ao executar esta versão sobre uma base V2.0.x existente.
alter table public.profiles add column if not exists email text;

create table if not exists public.squad_months (
  id uuid primary key default gen_random_uuid(),
  squad_id uuid not null references public.squads(id) on delete cascade,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  source_file text,
  latest_day int not null default 1 check (latest_day between 1 and 31),
  team_result text,
  redistributed numeric(12,2) not null default 0,
  team_goal_att numeric(12,2),
  team_goal_eval_pct numeric(8,6) not null default 0.343,
  score_settings jsonb not null default '{}'::jsonb,
  is_closed boolean not null default false,
  closed_at timestamptz,
  closed_by uuid references auth.users(id) on delete set null,
  closed_snapshot jsonb not null default '{}'::jsonb,
  imported_by uuid references auth.users(id) on delete set null,
  imported_at timestamptz not null default now(),
  unique (squad_id, year, month)
);

-- Compatibilidade ao executar esta versao sobre uma base anterior.
alter table public.squad_months add column if not exists score_settings jsonb not null default '{}'::jsonb;
alter table public.squad_months add column if not exists is_closed boolean not null default false;
alter table public.squad_months add column if not exists closed_at timestamptz;
alter table public.squad_months add column if not exists closed_by uuid references auth.users(id) on delete set null;
alter table public.squad_months add column if not exists closed_snapshot jsonb not null default '{}'::jsonb;

create table if not exists public.technician_monthly (
  id uuid primary key default gen_random_uuid(),
  squad_month_id uuid not null references public.squad_months(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  technician_name text not null,
  att numeric(12,2) not null default 0,
  notes5 numeric(12,2) not null default 0,
  notes4 numeric(12,2) not null default 0,
  notes3 numeric(12,2) not null default 0,
  notes2 numeric(12,2) not null default 0,
  notes1 numeric(12,2) not null default 0,
  total_eval numeric(12,2) not null default 0,
  avg_rating numeric(8,4) not null default 0,
  eval_pct numeric(8,6) not null default 0,
  status text,
  goals_hit int not null default 0,
  points numeric(14,2) not null default 0,
  rank int,
  discount numeric(14,2) not null default 0,
  point_bonus numeric(14,2) not null default 0,
  goal_att numeric(12,2) not null default 0,
  goal_eval numeric(12,2) not null default 0,
  unique (squad_month_id, technician_name)
);

create table if not exists public.daily_metrics (
  id bigint generated by default as identity primary key,
  technician_month_id uuid not null references public.technician_monthly(id) on delete cascade,
  day int not null check (day between 1 and 31),
  att numeric(12,2) not null default 0,
  notes5 numeric(12,2) not null default 0,
  off boolean not null default false,
  unique (technician_month_id, day)
);

create table if not exists public.quality_daily_metrics (
  id bigint generated by default as identity primary key,
  technician_month_id uuid not null references public.technician_monthly(id) on delete cascade,
  day int not null check (day between 1 and 31),
  quality_type text not null check (quality_type in ('product','company')),
  notes5 integer not null default 0 check (notes5 >= 0),
  notes4 integer not null default 0 check (notes4 >= 0),
  notes3 integer not null default 0 check (notes3 >= 0),
  notes2 integer not null default 0 check (notes2 >= 0),
  notes1 integer not null default 0 check (notes1 >= 0),
  source_file text,
  imported_by uuid,
  imported_at timestamptz not null default now(),
  constraint quality_daily_metrics_unique unique (technician_month_id, day, quality_type)
);

create table if not exists public.squad_themes (
  squad_id uuid primary key references public.squads(id) on delete cascade,
  theme jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_profiles_squad on public.profiles(squad_id);
create unique index if not exists idx_profiles_org_email_unique on public.profiles(organization_id, lower(email)) where email is not null;
create index if not exists idx_squad_months_squad on public.squad_months(squad_id);
create index if not exists idx_technician_monthly_month on public.technician_monthly(squad_month_id);
create index if not exists idx_technician_monthly_user on public.technician_monthly(user_id);
create index if not exists idx_daily_metrics_tech_month on public.daily_metrics(technician_month_id);
create index if not exists idx_quality_daily_metrics_tech_month on public.quality_daily_metrics(technician_month_id);

-- Helpers de autorizacao. SECURITY DEFINER evita recursao de RLS ao consultar profiles.
create or replace function public.current_profile()
returns public.profiles
language sql
stable
security definer
set search_path = public
as $$
  select p from public.profiles p
  where p.user_id = (select auth.uid()) and p.active = true
  limit 1;
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.role = 'super_admin'
  );
$$;

create or replace function public.can_read_squad(target_squad uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    join public.squads s on s.id = target_squad
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.organization_id = s.organization_id
      and (
        p.role = 'super_admin'
        or p.squad_id = target_squad
      )
  );
$$;

create or replace function public.can_admin_squad(target_squad uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    join public.squads s on s.id = target_squad
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.organization_id = s.organization_id
      and (
        p.role = 'super_admin'
        or (p.role = 'squad_admin' and p.squad_id = target_squad)
      )
  );
$$;

revoke all on function public.current_profile() from public;
revoke all on function public.is_super_admin() from public;
revoke all on function public.can_read_squad(uuid) from public;
revoke all on function public.can_admin_squad(uuid) from public;
grant execute on function public.current_profile() to authenticated;
grant execute on function public.is_super_admin() to authenticated;
grant execute on function public.can_read_squad(uuid) to authenticated;
grant execute on function public.can_admin_squad(uuid) to authenticated;

-- RLS
alter table public.organizations enable row level security;
alter table public.squads enable row level security;
alter table public.profiles enable row level security;
alter table public.squad_months enable row level security;
alter table public.technician_monthly enable row level security;
alter table public.daily_metrics enable row level security;
alter table public.quality_daily_metrics enable row level security;
alter table public.squad_themes enable row level security;

-- Organizations: usuario ve apenas a propria organizacao.
drop policy if exists org_select on public.organizations;
create policy org_select on public.organizations
for select to authenticated
using (id = (select (public.current_profile()).organization_id));

-- Squads: tecnico/admin do squad ve apenas o seu; super_admin ve todos da organizacao.
drop policy if exists squads_select on public.squads;
create policy squads_select on public.squads
for select to authenticated
using (public.can_read_squad(id));

-- Profiles: usuario ve o proprio perfil; admins podem ver perfis dentro do escopo que administram.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (
  user_id = (select auth.uid())
  or (squad_id is not null and public.can_admin_squad(squad_id))
  or (public.is_super_admin() and organization_id = (select (public.current_profile()).organization_id))
);

-- A criação cotidiana de usuários é feita pela Edge Function create-user com service_role.
-- Estas policies mantêm uma barreira adicional; a Data API do navegador recebe apenas SELECT em profiles.
-- Edicao direta de profiles fica reservada ao admin geral por seguranca.
drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles
for insert to authenticated
with check (public.is_super_admin());

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles
for update to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

-- Meses do squad.
drop policy if exists squad_months_select on public.squad_months;
create policy squad_months_select on public.squad_months
for select to authenticated
using (public.can_read_squad(squad_id));

drop policy if exists squad_months_insert on public.squad_months;
create policy squad_months_insert on public.squad_months
for insert to authenticated
with check (public.can_admin_squad(squad_id));

drop policy if exists squad_months_update on public.squad_months;
create policy squad_months_update on public.squad_months
for update to authenticated
using (public.can_admin_squad(squad_id))
with check (public.can_admin_squad(squad_id));

drop policy if exists squad_months_delete on public.squad_months;
create policy squad_months_delete on public.squad_months
for delete to authenticated
using (public.can_admin_squad(squad_id));

-- Resultados mensais: qualquer membro do mesmo Squad pode ver o ranking mensal.
drop policy if exists tech_month_select on public.technician_monthly;
create policy tech_month_select on public.technician_monthly
for select to authenticated
using (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_read_squad(sm.squad_id)
  )
);

drop policy if exists tech_month_insert on public.technician_monthly;
create policy tech_month_insert on public.technician_monthly
for insert to authenticated
with check (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists tech_month_update on public.technician_monthly;
create policy tech_month_update on public.technician_monthly
for update to authenticated
using (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists tech_month_delete on public.technician_monthly;
create policy tech_month_delete on public.technician_monthly
for delete to authenticated
using (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

-- Dia a dia: tecnico ve apenas o proprio detalhe. Admin do Squad ve todos do seu Squad.
drop policy if exists daily_select on public.daily_metrics;
create policy daily_select on public.daily_metrics
for select to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and (
        tm.user_id = (select auth.uid())
        or public.can_admin_squad(sm.squad_id)
      )
  )
);

drop policy if exists daily_insert on public.daily_metrics;
create policy daily_insert on public.daily_metrics
for insert to authenticated
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists daily_update on public.daily_metrics;
create policy daily_update on public.daily_metrics
for update to authenticated
using (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists daily_delete on public.daily_metrics;
create policy daily_delete on public.daily_metrics
for delete to authenticated
using (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

-- Qualidade diaria: mesma regra de leitura/administracao do detalhe diario operacional.
drop policy if exists quality_daily_select on public.quality_daily_metrics;
create policy quality_daily_select on public.quality_daily_metrics
for select to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and (
        tm.user_id = (select auth.uid())
        or public.can_admin_squad(sm.squad_id)
      )
  )
);

drop policy if exists quality_daily_insert on public.quality_daily_metrics;
create policy quality_daily_insert on public.quality_daily_metrics
for insert to authenticated
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_daily_update on public.quality_daily_metrics;
create policy quality_daily_update on public.quality_daily_metrics
for update to authenticated
using (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_daily_delete on public.quality_daily_metrics;
create policy quality_daily_delete on public.quality_daily_metrics
for delete to authenticated
using (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

-- Temas: todos do Squad leem; somente admins alteram.
drop policy if exists themes_select on public.squad_themes;
create policy themes_select on public.squad_themes
for select to authenticated
using (public.can_read_squad(squad_id));

drop policy if exists themes_insert on public.squad_themes;
create policy themes_insert on public.squad_themes
for insert to authenticated
with check (public.can_admin_squad(squad_id));

drop policy if exists themes_update on public.squad_themes;
create policy themes_update on public.squad_themes
for update to authenticated
using (public.can_admin_squad(squad_id))
with check (public.can_admin_squad(squad_id));

drop policy if exists themes_delete on public.squad_themes;
create policy themes_delete on public.squad_themes
for delete to authenticated
using (public.can_admin_squad(squad_id));

-- Permissoes da Data API. RLS continua sendo a camada que limita as linhas.
grant usage on schema public to authenticated;
grant select on public.organizations, public.squads to authenticated;
revoke insert, update, delete on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.squad_months to authenticated;
grant select, insert, update, delete on public.technician_monthly to authenticated;
grant select, insert, update, delete on public.daily_metrics to authenticated;
grant select, insert, update, delete on public.quality_daily_metrics to authenticated;
grant select, insert, update, delete on public.squad_themes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Estrutura inicial: Soften + 4 Squads.
insert into public.organizations (id,name,slug)
values ('10000000-0000-0000-0000-000000000001','Soften Sistemas','soften-sistemas')
on conflict (slug) do update set name=excluded.name;

insert into public.squads (id,organization_id,code,name)
values
 ('20000000-0000-0000-0000-00000000000a','10000000-0000-0000-0000-000000000001','A','Squad A'),
 ('20000000-0000-0000-0000-00000000000b','10000000-0000-0000-0000-000000000001','B','Squad B'),
 ('20000000-0000-0000-0000-00000000000d','10000000-0000-0000-0000-000000000001','D','Squad D'),
 ('20000000-0000-0000-0000-00000000000e','10000000-0000-0000-0000-000000000001','E','Squad E')
on conflict (organization_id,code) do update set name=excluded.name, active=true;


-- V2.11.0 - visão consolidada mensal por Squad (somente agregados).
-- Soften Performance Hub V2.11.0
-- Visão mensal consolidada por Squad para usuários autenticados da mesma organização.
-- Retorna apenas dados agregados de equipe; não expõe técnicos de outros Squads.

create or replace function public.get_org_squad_monthly_overview()
returns table (
  squad_code text,
  squad_name text,
  year integer,
  month integer,
  total_att bigint,
  total_eval bigint,
  eval_pct numeric,
  technician_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id
    from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
    limit 1
  )
  select
    s.code::text as squad_code,
    s.name::text as squad_name,
    sm.year,
    sm.month,
    coalesce(sum(tm.att), 0)::bigint as total_att,
    coalesce(sum(tm.total_eval), 0)::bigint as total_eval,
    case
      when coalesce(sum(tm.att), 0) > 0
        then coalesce(sum(tm.total_eval), 0)::numeric / sum(tm.att)::numeric
      else 0::numeric
    end as eval_pct,
    count(tm.id)::bigint as technician_count
  from me
  join public.squads s
    on s.organization_id = me.organization_id
   and s.active = true
  join public.squad_months sm
    on sm.squad_id = s.id
  left join public.technician_monthly tm
    on tm.squad_month_id = sm.id
  group by s.code, s.name, sm.year, sm.month
  order by sm.year, sm.month, s.code;
$$;

revoke all on function public.get_org_squad_monthly_overview() from public;
grant execute on function public.get_org_squad_monthly_overview() to authenticated;

-- ============================================================================
-- EVOLUÇÕES CUMULATIVAS ATÉ A V2.29.9
-- ============================================================================

-- >>> MIGRACAO_V2.13.0.sql
-- Soften Performance Hub V2.13.0
-- Libera para usuarios autenticados da mesma organizacao:
-- 1) consolidado mensal por Squad;
-- 2) comparativo mensal dos tecnicos de todos os Squads.
-- Nao expoe e-mail, senha, bonus, desconto ou dados de autenticacao.

create or replace function public.get_org_squad_monthly_overview()
returns table (
  squad_code text,
  squad_name text,
  year integer,
  month integer,
  total_att bigint,
  total_eval bigint,
  eval_pct numeric,
  technician_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id
    from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
    limit 1
  )
  select
    s.code::text as squad_code,
    s.name::text as squad_name,
    sm.year,
    sm.month,
    coalesce(sum(tm.att), 0)::bigint as total_att,
    coalesce(sum(tm.total_eval), 0)::bigint as total_eval,
    case when coalesce(sum(tm.att), 0) > 0
      then coalesce(sum(tm.total_eval), 0)::numeric / sum(tm.att)::numeric
      else 0::numeric end as eval_pct,
    count(tm.id)::bigint as technician_count
  from me
  join public.squads s on s.organization_id = me.organization_id and s.active = true
  join public.squad_months sm on sm.squad_id = s.id
  left join public.technician_monthly tm on tm.squad_month_id = sm.id
  group by s.code, s.name, sm.year, sm.month
  order by sm.year, sm.month, s.code;
$$;

revoke all on function public.get_org_squad_monthly_overview() from public;
grant execute on function public.get_org_squad_monthly_overview() to authenticated;

create or replace function public.get_org_technician_monthly_overview()
returns table (
  squad_code text,
  squad_name text,
  year integer,
  month integer,
  technician_name text,
  att bigint,
  total_eval bigint,
  avg_rating numeric,
  eval_pct numeric,
  points numeric,
  status text
)
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id
    from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
    limit 1
  )
  select
    s.code::text as squad_code,
    s.name::text as squad_name,
    sm.year,
    sm.month,
    tm.technician_name::text,
    coalesce(tm.att,0)::bigint as att,
    coalesce(tm.total_eval,0)::bigint as total_eval,
    coalesce(tm.avg_rating,0)::numeric as avg_rating,
    coalesce(tm.eval_pct,0)::numeric as eval_pct,
    coalesce(tm.points,0)::numeric as points,
    coalesce(tm.status,'')::text as status
  from me
  join public.squads s on s.organization_id = me.organization_id and s.active = true
  join public.squad_months sm on sm.squad_id = s.id
  join public.technician_monthly tm on tm.squad_month_id = sm.id
  where nullif(btrim(tm.technician_name), '') is not null
  order by sm.year, sm.month, s.code, tm.technician_name;
$$;

revoke all on function public.get_org_technician_monthly_overview() from public;
grant execute on function public.get_org_technician_monthly_overview() to authenticated;
-- <<< MIGRACAO_V2.13.0.sql

-- >>> MIGRACAO_V2.14.0.sql
-- Soften Performance Hub V2.14.0
-- Consolidado diario de atendimentos por Squad para usuarios autenticados da mesma organizacao.
-- Retorna somente totais agregados por Squad/dia. Nao expoe dados individuais.

create or replace function public.get_org_daily_attendance_overview()
returns table (
  squad_code text,
  year integer,
  month integer,
  day integer,
  total_att bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id
    from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
    limit 1
  )
  select
    s.code::text as squad_code,
    sm.year,
    sm.month,
    dm.day,
    coalesce(sum(dm.att),0)::bigint as total_att
  from me
  join public.squads s
    on s.organization_id = me.organization_id
   and s.active = true
  join public.squad_months sm
    on sm.squad_id = s.id
  join public.technician_monthly tm
    on tm.squad_month_id = sm.id
  join public.daily_metrics dm
    on dm.technician_month_id = tm.id
   and dm.day <= sm.latest_day
   and coalesce(dm.off,false) = false
  group by s.code, sm.year, sm.month, dm.day
  order by sm.year, sm.month, dm.day, s.code;
$$;

revoke all on function public.get_org_daily_attendance_overview() from public;
grant execute on function public.get_org_daily_attendance_overview() to authenticated;
-- <<< MIGRACAO_V2.14.0.sql

-- >>> MIGRACAO_V2.18.0.sql
-- Soften Performance Hub V2.18.0
-- Bonificacao financeira separada da gamificacao + comissao manual do Admin Geral.
-- Execute UMA VEZ antes de publicar o frontend V2.18.0.

begin;

alter table public.squad_months
  add column if not exists finance_settings jsonb not null default '{}'::jsonb;

alter table public.squad_months
  add column if not exists finance_month_data jsonb not null default '{}'::jsonb;

create table if not exists public.technician_finance_monthly (
  id uuid primary key default gen_random_uuid(),
  technician_month_id uuid not null unique references public.technician_monthly(id) on delete cascade,
  manual_bonus numeric(14,2) not null default 0,
  sales_commission numeric(14,2) not null default 0,
  vacation boolean not null default false,
  calculated jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.super_admin_commissions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  amount numeric(14,2) not null default 0,
  notes text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (organization_id,user_id,year,month)
);

create index if not exists idx_tech_finance_month on public.technician_finance_monthly(technician_month_id);
create index if not exists idx_super_admin_commission_period on public.super_admin_commissions(organization_id,year,month);

alter table public.technician_finance_monthly enable row level security;
alter table public.super_admin_commissions enable row level security;

drop policy if exists tech_finance_select on public.technician_finance_monthly;
create policy tech_finance_select on public.technician_finance_monthly
for select to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id=tm.squad_month_id
    where tm.id=technician_finance_monthly.technician_month_id
      and (tm.user_id=(select auth.uid()) or public.can_admin_squad(sm.squad_id))
  )
);

drop policy if exists tech_finance_insert on public.technician_finance_monthly;
create policy tech_finance_insert on public.technician_finance_monthly
for insert to authenticated
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id=tm.squad_month_id
    where tm.id=technician_finance_monthly.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists tech_finance_update on public.technician_finance_monthly;
create policy tech_finance_update on public.technician_finance_monthly
for update to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id=tm.squad_month_id
    where tm.id=technician_finance_monthly.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id=tm.squad_month_id
    where tm.id=technician_finance_monthly.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists tech_finance_delete on public.technician_finance_monthly;
create policy tech_finance_delete on public.technician_finance_monthly
for delete to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id=tm.squad_month_id
    where tm.id=technician_finance_monthly.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists super_admin_commission_select on public.super_admin_commissions;
create policy super_admin_commission_select on public.super_admin_commissions
for select to authenticated
using (public.is_super_admin() and organization_id=(select (public.current_profile()).organization_id));

drop policy if exists super_admin_commission_insert on public.super_admin_commissions;
create policy super_admin_commission_insert on public.super_admin_commissions
for insert to authenticated
with check (
  public.is_super_admin()
  and organization_id=(select (public.current_profile()).organization_id)
  and user_id=(select auth.uid())
);

drop policy if exists super_admin_commission_update on public.super_admin_commissions;
create policy super_admin_commission_update on public.super_admin_commissions
for update to authenticated
using (
  public.is_super_admin()
  and organization_id=(select (public.current_profile()).organization_id)
  and user_id=(select auth.uid())
)
with check (
  public.is_super_admin()
  and organization_id=(select (public.current_profile()).organization_id)
  and user_id=(select auth.uid())
);

comment on column public.squad_months.finance_settings is 'Faixas e parametros da bonificacao financeira vigentes para o Squad/mes.';
comment on column public.squad_months.finance_month_data is 'Dados mensais do financeiro, como clientes no inicio e cancelamentos.';
comment on table public.technician_finance_monthly is 'Dados financeiros mensais protegidos: visiveis apenas ao proprio tecnico ou admins do Squad.';
comment on table public.super_admin_commissions is 'Comissao mensal manual dos usuarios Admin Geral.';

commit;
-- <<< MIGRACAO_V2.18.0.sql

-- >>> MIGRACAO_V2.19.0.sql
-- Soften Performance Hub V2.19.0
-- Dois modelos financeiros + histórico de movimentação de Squad.
-- Execute UMA VEZ antes de publicar o frontend V2.19.0.

begin;

alter table public.squad_months
  add column if not exists finance_model text not null default 'squad';

alter table public.squad_months
  drop constraint if exists squad_months_finance_model_check;

alter table public.squad_months
  add constraint squad_months_finance_model_check
  check (finance_model in ('squad','individual'));

alter table public.squad_months
  add column if not exists finance_compare boolean not null default true;

alter table public.squad_months
  add column if not exists finance_comparison_snapshot jsonb not null default '{}'::jsonb;

create table if not exists public.profile_squad_history (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  squad_id uuid not null references public.squads(id) on delete cascade,
  technician_name text,
  valid_from_year int not null check (valid_from_year between 2020 and 2100),
  valid_from_month int not null check (valid_from_month between 1 and 12),
  valid_to_year int check (valid_to_year between 2020 and 2100),
  valid_to_month int check (valid_to_month between 1 and 12),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  note text,
  check ((valid_to_year is null and valid_to_month is null) or (valid_to_year is not null and valid_to_month is not null))
);

alter table public.profile_squad_history add column if not exists technician_name text;

create index if not exists idx_profile_squad_history_user on public.profile_squad_history(user_id,valid_from_year,valid_from_month);
create index if not exists idx_profile_squad_history_squad on public.profile_squad_history(squad_id,valid_from_year,valid_from_month);

-- Evita dois vínculos abertos simultaneamente por usuário.
create unique index if not exists idx_profile_squad_history_open_unique
on public.profile_squad_history(user_id)
where valid_to_year is null and valid_to_month is null;

-- Cria o vínculo aberto inicial para técnicos já existentes. Quando há histórico mensal
-- já ligado pelo user_id, usa a primeira competência conhecida; caso contrário usa a
-- competência de criação do perfil. Isso prepara a base para futuras movimentações.
insert into public.profile_squad_history (
  organization_id,user_id,squad_id,technician_name,
  valid_from_year,valid_from_month,note
)
select
  p.organization_id,p.user_id,p.squad_id,p.technician_name,
  coalesce(first_month.year, extract(year from p.created_at)::int),
  coalesce(first_month.month, extract(month from p.created_at)::int),
  'Vínculo atual inicializado na migração V2.19.0.'
from public.profiles p
left join lateral (
  select sm.year, sm.month
  from public.technician_monthly tm
  join public.squad_months sm on sm.id=tm.squad_month_id
  where tm.user_id=p.user_id and sm.squad_id=p.squad_id
  order by sm.year,sm.month
  limit 1
) first_month on true
where p.role='technician'
  and p.squad_id is not null
  and not exists (
    select 1 from public.profile_squad_history h
    where h.user_id=p.user_id and h.valid_to_year is null and h.valid_to_month is null
  );

alter table public.profile_squad_history enable row level security;

drop policy if exists profile_squad_history_select on public.profile_squad_history;
create policy profile_squad_history_select on public.profile_squad_history
for select to authenticated
using (
  user_id=(select auth.uid())
  or public.is_super_admin()
  or public.can_admin_squad(squad_id)
);

-- Escrita é feita somente pelas Edge Functions com service_role.
revoke insert, update, delete on public.profile_squad_history from authenticated;
grant select on public.profile_squad_history to authenticated;

comment on column public.squad_months.finance_model is 'Modelo oficial de bonificacao do mes: squad (base compartilhada) ou individual.';
comment on column public.squad_months.finance_compare is 'Quando true, exibe comparacao dos dois modelos financeiros.';
comment on column public.squad_months.finance_comparison_snapshot is 'Snapshot comparativo dos dois modelos no fechamento.';
comment on table public.profile_squad_history is 'Historico de vigencia do vinculo de usuarios a Squads. Movimentacoes futuras devem preservar meses anteriores.';

commit;
-- <<< MIGRACAO_V2.19.0.sql

-- >>> MIGRACAO_V2.20.0.sql
-- Soften Performance Hub V2.20.0
-- Transicao financeira para tecnicos + teto global do modelo Individual + ranking financeiro do Squad.
-- Execute UMA VEZ antes de publicar o frontend V2.20.0.

begin;

alter table public.squad_months
  add column if not exists finance_technician_compare boolean not null default false;

alter table public.squad_months
  add column if not exists finance_individual_cap numeric(14,2) not null default 7000;

alter table public.squad_months
  drop constraint if exists squad_months_finance_individual_cap_check;

alter table public.squad_months
  add constraint squad_months_finance_individual_cap_check
  check (finance_individual_cap >= 0);

comment on column public.squad_months.finance_technician_compare is
  'Quando true, o tecnico visualiza uma simulacao do modelo financeiro alternativo no Meu desempenho.';

comment on column public.squad_months.finance_individual_cap is
  'Teto da soma mensal paga aos tecnicos do Squad quando calculado o modelo Individual.';

-- Ranking financeiro: tecnicos podem ver apenas nome + valor oficial dos colegas do proprio Squad.
-- Nao expoe bonus manual, vendas, desconto, redistribuicao, teto ou demais componentes internos.
create or replace function public.get_my_squad_finance_ranking(p_year int, p_month int)
returns table (
  technician_name text,
  amount numeric,
  ranking bigint,
  finance_model text
)
language sql
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id, p.squad_id, p.role
    from public.profiles p
    where p.user_id = auth.uid()
      and p.active = true
    limit 1
  ), rows as (
    select
      tm.technician_name,
      coalesce((tf.calculated->>'final')::numeric, 0) as amount,
      sm.finance_model
    from me
    join public.squad_months sm
      on sm.squad_id = me.squad_id
     and sm.year = p_year
     and sm.month = p_month
    join public.technician_monthly tm on tm.squad_month_id = sm.id
    left join public.technician_finance_monthly tf on tf.technician_month_id = tm.id
    where me.squad_id is not null
      and me.role in ('technician','squad_admin')
  )
  select
    r.technician_name,
    r.amount,
    dense_rank() over (order by r.amount desc) as ranking,
    r.finance_model
  from rows r
  order by amount desc, technician_name asc;
$$;

revoke all on function public.get_my_squad_finance_ranking(int,int) from public;
grant execute on function public.get_my_squad_finance_ranking(int,int) to authenticated;

commit;
-- <<< MIGRACAO_V2.20.0.sql

-- >>> MIGRACAO_V2.20.5.sql
-- Soften Performance Hub V2.20.5
-- Permite retirar um técnico apenas do denominador da quantidade de técnicos
-- usada no modelo financeiro Base do Squad, preservando seus atendimentos e notas.

alter table if exists public.technician_finance_monthly
  add column if not exists exclude_from_group_count boolean not null default false;

comment on column public.technician_finance_monthly.exclude_from_group_count is
  'Quando true, os dados do técnico continuam nos totais do mês, mas ele não entra na quantidade de técnicos usada para a média de atendimentos/técnico/dia da Base do Squad.';
-- <<< MIGRACAO_V2.20.5.sql

-- >>> MIGRACAO_V2.21.0.sql
-- Soften Performance Hub V2.21.0
-- Filtros analiticos por dia.
-- Preserva a competencia mensal para pontuacao oficial, fechamento e bonificacao.

begin;

alter table if exists public.daily_metrics
  add column if not exists notes4 integer not null default 0,
  add column if not exists notes3 integer not null default 0,
  add column if not exists notes2 integer not null default 0,
  add column if not exists notes1 integer not null default 0;

comment on column public.daily_metrics.notes4 is 'Quantidade diaria de avaliacoes nota 4 importadas do CSV.';
comment on column public.daily_metrics.notes3 is 'Quantidade diaria de avaliacoes nota 3 importadas do CSV.';
comment on column public.daily_metrics.notes2 is 'Quantidade diaria de avaliacoes nota 2 importadas do CSV.';
comment on column public.daily_metrics.notes1 is 'Quantidade diaria de avaliacoes nota 1 importadas do CSV.';

-- A funcao agregada anterior ja existia nas versoes recentes. Ela precisa ser
-- recriada para devolver tambem a composicao diaria das avaliacoes.
drop function if exists public.get_org_daily_attendance_overview();

create function public.get_org_daily_attendance_overview()
returns table (
  squad_code text,
  year integer,
  month integer,
  day integer,
  total_att bigint,
  notes5 bigint,
  notes4 bigint,
  notes3 bigint,
  notes2 bigint,
  notes1 bigint,
  total_eval bigint,
  eval_pct numeric
)
language sql
security definer
set search_path = public
as $$
  select
    s.code::text as squad_code,
    sm.year,
    sm.month,
    dm.day,
    coalesce(sum(dm.att),0)::bigint as total_att,
    coalesce(sum(dm.notes5),0)::bigint as notes5,
    coalesce(sum(dm.notes4),0)::bigint as notes4,
    coalesce(sum(dm.notes3),0)::bigint as notes3,
    coalesce(sum(dm.notes2),0)::bigint as notes2,
    coalesce(sum(dm.notes1),0)::bigint as notes1,
    coalesce(sum(dm.notes5 + dm.notes4 + dm.notes3 + dm.notes2 + dm.notes1),0)::bigint as total_eval,
    case
      when coalesce(sum(dm.att),0) = 0 then 0::numeric
      else coalesce(sum(dm.notes5 + dm.notes4 + dm.notes3 + dm.notes2 + dm.notes1),0)::numeric / sum(dm.att)::numeric
    end as eval_pct
  from public.daily_metrics dm
  join public.technician_monthly tm on tm.id = dm.technician_month_id
  join public.squad_months sm on sm.id = tm.squad_month_id
  join public.squads s on s.id = sm.squad_id
  where exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and p.organization_id = s.organization_id
      and coalesce(p.active, true) = true
  )
  group by s.code, sm.year, sm.month, dm.day
  order by sm.year, sm.month, dm.day, s.code;
$$;

revoke all on function public.get_org_daily_attendance_overview() from public;
grant execute on function public.get_org_daily_attendance_overview() to authenticated;

-- Versao diaria do consolidado de tecnicos usada pelo grafico geral em tela cheia.
-- Entrega somente metricas operacionais; nao expoe e-mail, bonus manuais,
-- comissao de vendas, ferias ou componentes internos do financeiro.
drop function if exists public.get_org_technician_daily_overview();

create function public.get_org_technician_daily_overview()
returns table (
  squad_code text,
  year integer,
  month integer,
  day integer,
  technician_name text,
  att bigint,
  notes5 bigint,
  notes4 bigint,
  notes3 bigint,
  notes2 bigint,
  notes1 bigint,
  total_eval bigint,
  avg_rating numeric,
  eval_pct numeric
)
language sql
security definer
set search_path = public
as $$
  select
    s.code::text as squad_code,
    sm.year,
    sm.month,
    dm.day,
    tm.technician_name::text,
    coalesce(sum(dm.att),0)::bigint as att,
    coalesce(sum(dm.notes5),0)::bigint as notes5,
    coalesce(sum(dm.notes4),0)::bigint as notes4,
    coalesce(sum(dm.notes3),0)::bigint as notes3,
    coalesce(sum(dm.notes2),0)::bigint as notes2,
    coalesce(sum(dm.notes1),0)::bigint as notes1,
    coalesce(sum(dm.notes5 + dm.notes4 + dm.notes3 + dm.notes2 + dm.notes1),0)::bigint as total_eval,
    case
      when coalesce(sum(dm.notes5 + dm.notes4 + dm.notes3 + dm.notes2 + dm.notes1),0) = 0 then 0::numeric
      else (
        sum(dm.notes5 * 5 + dm.notes4 * 4 + dm.notes3 * 3 + dm.notes2 * 2 + dm.notes1)::numeric
        / sum(dm.notes5 + dm.notes4 + dm.notes3 + dm.notes2 + dm.notes1)::numeric
      )
    end as avg_rating,
    case
      when coalesce(sum(dm.att),0) = 0 then 0::numeric
      else sum(dm.notes5 + dm.notes4 + dm.notes3 + dm.notes2 + dm.notes1)::numeric / sum(dm.att)::numeric
    end as eval_pct
  from public.daily_metrics dm
  join public.technician_monthly tm on tm.id = dm.technician_month_id
  join public.squad_months sm on sm.id = tm.squad_month_id
  join public.squads s on s.id = sm.squad_id
  where exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and p.organization_id = s.organization_id
      and coalesce(p.active, true) = true
  )
  group by s.code, sm.year, sm.month, dm.day, tm.technician_name
  order by sm.year, sm.month, dm.day, s.code, tm.technician_name;
$$;

revoke all on function public.get_org_technician_daily_overview() from public;
grant execute on function public.get_org_technician_daily_overview() to authenticated;

commit;
-- <<< MIGRACAO_V2.21.0.sql

-- >>> MIGRACAO_V2.24.2.sql
-- Soften Performance Hub V2.24.2
-- Ranking do game para técnicos: expõe somente o consolidado/ranking do próprio Squad.

begin;

drop function if exists public.get_my_squad_game_ranking(date,date);

create function public.get_my_squad_game_ranking(
  p_start_date date,
  p_end_date date
)
returns table (
  technician_name text,
  att bigint,
  notes5 bigint,
  notes4 bigint,
  notes3 bigint,
  notes2 bigint,
  notes1 bigint,
  total_eval bigint,
  avg_rating numeric,
  eval_pct numeric,
  points numeric,
  goals_hit integer,
  status text,
  ranking bigint
)
language sql
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id, p.squad_id, p.role
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
    limit 1
  ), base as (
    select
      tm.technician_name::text as technician_name,
      coalesce(sum(dm.att),0)::bigint as att,
      coalesce(sum(dm.notes5),0)::bigint as notes5,
      coalesce(sum(dm.notes4),0)::bigint as notes4,
      coalesce(sum(dm.notes3),0)::bigint as notes3,
      coalesce(sum(dm.notes2),0)::bigint as notes2,
      coalesce(sum(dm.notes1),0)::bigint as notes1
    from me
    join public.squad_months sm on sm.squad_id = me.squad_id
    join public.technician_monthly tm on tm.squad_month_id = sm.id
    join public.daily_metrics dm on dm.technician_month_id = tm.id
    where me.squad_id is not null
      and me.role in ('technician','squad_admin')
      and make_date(sm.year,sm.month,dm.day) between least(p_start_date,p_end_date) and greatest(p_start_date,p_end_date)
      and dm.day <= coalesce(sm.latest_day,dm.day)
    group by tm.technician_name
  ), metrics as (
    select
      b.*,
      (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::bigint as total_eval,
      case when (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)=0 then 0::numeric
        else trunc(((b.notes5*5+b.notes4*4+b.notes3*3+b.notes2*2+b.notes1)::numeric/(b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::numeric),2)
      end as avg_rating,
      case when b.att=0 then 0::numeric
        else round(((b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::numeric/b.att::numeric),4)
      end as eval_pct
    from base b
    where b.att>0 or (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)>0
  ), refs as (
    select
      round(avg(att)::numeric,0) as ref_att,
      round(avg(total_eval)::numeric,0) as ref_total_eval,
      trunc(avg(avg_rating)::numeric,2) as ref_avg,
      round(avg(eval_pct)::numeric,4) as ref_eval_pct
    from metrics
  ), scored as (
    select
      m.*,
      ((case when m.att>=r.ref_att then 1 else 0 end)+
       (case when m.total_eval>=r.ref_total_eval then 1 else 0 end)+
       (case when m.avg_rating>=r.ref_avg then 1 else 0 end)+
       (case when m.eval_pct>=r.ref_eval_pct then 1 else 0 end))::integer as goals_hit,
      round(
        m.att::numeric*m.avg_rating
        + case when m.att>=r.ref_att then 20 else -20 end
        + case when m.total_eval>=r.ref_total_eval then 30 else -30 end
        + case when m.avg_rating>=r.ref_avg then 40 else -40 end
        + case when m.eval_pct>=r.ref_eval_pct then 35 else -35 end
      ,2) as points
    from metrics m cross join refs r
  ), ranked as (
    select s.*, row_number() over(order by s.points desc, s.att desc, s.technician_name asc) as ranking
    from scored s
  )
  select
    r.technician_name,r.att,r.notes5,r.notes4,r.notes3,r.notes2,r.notes1,r.total_eval,
    r.avg_rating,r.eval_pct,r.points,r.goals_hit,
    case when r.goals_hit>=2 then 'ACIMA' else 'ABAIXO' end::text as status,
    r.ranking
  from ranked r
  order by r.ranking;
$$;

revoke all on function public.get_my_squad_game_ranking(date,date) from public;
grant execute on function public.get_my_squad_game_ranking(date,date) to authenticated;

commit;
-- <<< MIGRACAO_V2.24.2.sql

-- >>> MIGRACAO_V2.25.1.sql
-- Soften Performance Hub V2.25.1
-- Feedbacks mensais por tecnico, com RLS por organizacao/Squad e leitura opcional pelo proprio tecnico.

begin;

create table if not exists public.technician_feedbacks (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  squad_id uuid not null references public.squads(id) on delete cascade,
  technician_user_id uuid null,
  technician_name text not null,
  year integer not null check (year between 2020 and 2100),
  month integer not null check (month between 1 and 12),
  summary text not null default '',
  strengths text not null default '',
  improvement_points text not null default '',
  next_month_goals text not null default '',
  manager_notes text not null default '',
  status text not null default 'draft' check (status in ('draft','finalized')),
  visible_to_technician boolean not null default false,
  generated_snapshot jsonb not null default '{}'::jsonb,
  created_by uuid null,
  updated_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finalized_at timestamptz null,
  constraint technician_feedbacks_month_unique unique (organization_id, squad_id, year, month, technician_name)
);

create index if not exists technician_feedbacks_scope_idx
  on public.technician_feedbacks (organization_id, squad_id, year, month);

create index if not exists technician_feedbacks_technician_idx
  on public.technician_feedbacks (technician_user_id, year desc, month desc);

alter table public.technician_feedbacks enable row level security;

-- Recria as policies para que a migracao possa ser executada novamente com seguranca.
drop policy if exists technician_feedbacks_select on public.technician_feedbacks;
drop policy if exists technician_feedbacks_insert on public.technician_feedbacks;
drop policy if exists technician_feedbacks_update on public.technician_feedbacks;
drop policy if exists technician_feedbacks_delete on public.technician_feedbacks;

create policy technician_feedbacks_select
on public.technician_feedbacks
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
      and p.organization_id = technician_feedbacks.organization_id
      and (
        p.role = 'super_admin'
        or (p.role = 'squad_admin' and p.squad_id = technician_feedbacks.squad_id)
        or (
          p.role = 'technician'
          and technician_feedbacks.technician_user_id = auth.uid()
          and technician_feedbacks.status = 'finalized'
          and technician_feedbacks.visible_to_technician = true
        )
      )
  )
);

create policy technician_feedbacks_insert
on public.technician_feedbacks
for insert
to authenticated
with check (
  exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
      and p.organization_id = technician_feedbacks.organization_id
      and (
        p.role = 'super_admin'
        or (p.role = 'squad_admin' and p.squad_id = technician_feedbacks.squad_id)
      )
  )
);

create policy technician_feedbacks_update
on public.technician_feedbacks
for update
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
      and p.organization_id = technician_feedbacks.organization_id
      and (
        p.role = 'super_admin'
        or (p.role = 'squad_admin' and p.squad_id = technician_feedbacks.squad_id)
      )
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
      and p.organization_id = technician_feedbacks.organization_id
      and (
        p.role = 'super_admin'
        or (p.role = 'squad_admin' and p.squad_id = technician_feedbacks.squad_id)
      )
  )
);

create policy technician_feedbacks_delete
on public.technician_feedbacks
for delete
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
      and p.organization_id = technician_feedbacks.organization_id
      and (
        p.role = 'super_admin'
        or (p.role = 'squad_admin' and p.squad_id = technician_feedbacks.squad_id)
      )
  )
);

grant select, insert, update, delete on public.technician_feedbacks to authenticated;

commit;
-- <<< MIGRACAO_V2.25.1.sql

-- >>> MIGRACAO_V2.26.0.sql
-- Soften Performance Hub V2.26.0
-- Qualidade: importacao independente de notas de Produto/Empresa por tecnico/dia.
-- A coluna NotaServico do CSV de qualidade nao e armazenada nem utilizada em calculos.

begin;

create table if not exists public.quality_daily_metrics (
  id bigint generated by default as identity primary key,
  technician_month_id uuid not null references public.technician_monthly(id) on delete cascade,
  day integer not null check (day between 1 and 31),
  quality_type text not null check (quality_type in ('product','company')),
  notes5 integer not null default 0 check (notes5 >= 0),
  notes4 integer not null default 0 check (notes4 >= 0),
  notes3 integer not null default 0 check (notes3 >= 0),
  notes2 integer not null default 0 check (notes2 >= 0),
  notes1 integer not null default 0 check (notes1 >= 0),
  source_file text,
  imported_by uuid null,
  imported_at timestamptz not null default now(),
  constraint quality_daily_metrics_unique unique (technician_month_id, day, quality_type)
);

create index if not exists idx_quality_daily_metrics_tech_month
  on public.quality_daily_metrics (technician_month_id);

create index if not exists idx_quality_daily_metrics_type
  on public.quality_daily_metrics (quality_type, day);

comment on table public.quality_daily_metrics is 'Consolidado diario das avaliacoes de Produto e Empresa. Servico continua exclusivamente em daily_metrics.';
comment on column public.quality_daily_metrics.quality_type is 'product ou company. NotaServico do CSV de qualidade e ignorada pelo frontend.';

alter table public.quality_daily_metrics enable row level security;

drop policy if exists quality_daily_select on public.quality_daily_metrics;
create policy quality_daily_select on public.quality_daily_metrics
for select to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and (
        tm.user_id = (select auth.uid())
        or public.can_admin_squad(sm.squad_id)
      )
  )
);

drop policy if exists quality_daily_insert on public.quality_daily_metrics;
create policy quality_daily_insert on public.quality_daily_metrics
for insert to authenticated
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_daily_update on public.quality_daily_metrics;
create policy quality_daily_update on public.quality_daily_metrics
for update to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_daily_delete on public.quality_daily_metrics;
create policy quality_daily_delete on public.quality_daily_metrics
for delete to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

grant select, insert, update, delete on public.quality_daily_metrics to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
-- <<< MIGRACAO_V2.26.0.sql

-- >>> MIGRACAO_V2.27.0.sql
-- Soften Performance Hub V2.27.0
-- Qualidade independente do technician_monthly.
-- Permite manter Produto/Empresa de tecnicos que nao aparecem no CSV operacional da competencia.

begin;

create table if not exists public.quality_person_daily_metrics (
  id bigint generated by default as identity primary key,
  squad_month_id uuid not null references public.squad_months(id) on delete cascade,
  technician_name text not null,
  technician_key text not null,
  day integer not null check (day between 1 and 31),
  quality_type text not null check (quality_type in ('product','company')),
  notes5 integer not null default 0 check (notes5 >= 0),
  notes4 integer not null default 0 check (notes4 >= 0),
  notes3 integer not null default 0 check (notes3 >= 0),
  notes2 integer not null default 0 check (notes2 >= 0),
  notes1 integer not null default 0 check (notes1 >= 0),
  source_file text,
  imported_by uuid null,
  imported_at timestamptz not null default now(),
  constraint quality_person_daily_metrics_unique unique (squad_month_id, technician_key, day, quality_type)
);

create index if not exists idx_quality_person_daily_month
  on public.quality_person_daily_metrics (squad_month_id);

create index if not exists idx_quality_person_daily_tech
  on public.quality_person_daily_metrics (squad_month_id, technician_key);

create index if not exists idx_quality_person_daily_type_day
  on public.quality_person_daily_metrics (quality_type, day);

comment on table public.quality_person_daily_metrics is
'Qualidade Produto/Empresa por tecnico e dia, independente de existir linha operacional em technician_monthly.';

-- Preserva dados ja importados na V2.26. A proxima reimportacao da qualidade
-- substitui integralmente os registros da competencia/squad nesta nova tabela.
insert into public.quality_person_daily_metrics (
  squad_month_id, technician_name, technician_key, day, quality_type,
  notes5, notes4, notes3, notes2, notes1, source_file, imported_by, imported_at
)
select
  tm.squad_month_id,
  tm.technician_name,
  lower(regexp_replace(trim(tm.technician_name), '[[:space:]]+', '', 'g')),
  q.day,
  q.quality_type,
  q.notes5, q.notes4, q.notes3, q.notes2, q.notes1,
  q.source_file, q.imported_by, q.imported_at
from public.quality_daily_metrics q
join public.technician_monthly tm on tm.id = q.technician_month_id
on conflict (squad_month_id, technician_key, day, quality_type)
do update set
  technician_name = excluded.technician_name,
  notes5 = excluded.notes5,
  notes4 = excluded.notes4,
  notes3 = excluded.notes3,
  notes2 = excluded.notes2,
  notes1 = excluded.notes1,
  source_file = excluded.source_file,
  imported_by = excluded.imported_by,
  imported_at = excluded.imported_at;

alter table public.quality_person_daily_metrics enable row level security;

drop policy if exists quality_person_daily_select on public.quality_person_daily_metrics;
create policy quality_person_daily_select on public.quality_person_daily_metrics
for select to authenticated
using (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_person_daily_insert on public.quality_person_daily_metrics;
create policy quality_person_daily_insert on public.quality_person_daily_metrics
for insert to authenticated
with check (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_person_daily_update on public.quality_person_daily_metrics;
create policy quality_person_daily_update on public.quality_person_daily_metrics
for update to authenticated
using (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_person_daily_delete on public.quality_person_daily_metrics;
create policy quality_person_daily_delete on public.quality_person_daily_metrics
for delete to authenticated
using (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

grant select, insert, update, delete on public.quality_person_daily_metrics to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
-- <<< MIGRACAO_V2.27.0.sql

-- >>> MIGRACAO_V2.28.0.sql
-- Soften Performance Hub V2.28.0
-- Base historica e confidencial de custo-hora do suporte tecnico.
-- Escopo organizacional: nao pertence a um Squad.

begin;

create table if not exists public.support_technician_hourly_costs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  technician_user_id uuid null,
  technician_name text not null,
  technician_key text not null,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  hourly_cost numeric(12,2) not null default 0 check (hourly_cost >= 0),
  updated_by uuid null references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint support_technician_hourly_costs_unique unique (organization_id, year, month, technician_key)
);

create index if not exists idx_support_hourly_costs_period
  on public.support_technician_hourly_costs (organization_id, year, month);

create index if not exists idx_support_hourly_costs_technician
  on public.support_technician_hourly_costs (organization_id, technician_key, year, month);

comment on table public.support_technician_hourly_costs is
'Base historica confidencial de custo-hora por tecnico e competencia. Uso futuro em analises de custo de atendimento do suporte como um todo.';

alter table public.support_technician_hourly_costs enable row level security;

drop policy if exists support_hourly_costs_select on public.support_technician_hourly_costs;
create policy support_hourly_costs_select on public.support_technician_hourly_costs
for select to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_hourly_costs_insert on public.support_technician_hourly_costs;
create policy support_hourly_costs_insert on public.support_technician_hourly_costs
for insert to authenticated
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_hourly_costs_update on public.support_technician_hourly_costs;
create policy support_hourly_costs_update on public.support_technician_hourly_costs
for update to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
)
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_hourly_costs_delete on public.support_technician_hourly_costs;
create policy support_hourly_costs_delete on public.support_technician_hourly_costs
for delete to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

grant select, insert, update, delete on public.support_technician_hourly_costs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
-- <<< MIGRACAO_V2.28.0.sql

-- >>> MIGRACAO_V2.28.1.sql
-- Soften Performance Hub V2.28.1
-- Simplifica a base de custos: custo geral mensal do Suporte, sem valores individuais por tecnico.
-- A tabela da V2.28.0 e mantida apenas por compatibilidade/historico e deixa de ser usada pela tela.

begin;

create table if not exists public.support_monthly_costs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  payroll_cost numeric(14,2) not null default 0 check (payroll_cost >= 0),
  other_costs numeric(14,2) not null default 0 check (other_costs >= 0),
  technician_count int not null default 1 check (technician_count >= 1),
  hours_per_day numeric(5,2) not null default 8 check (hours_per_day > 0 and hours_per_day <= 24),
  updated_by uuid null references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint support_monthly_costs_unique unique (organization_id, year, month)
);

create index if not exists idx_support_monthly_costs_period
  on public.support_monthly_costs (organization_id, year, month);

comment on table public.support_monthly_costs is
'Base confidencial de custo geral mensal do Suporte tecnico. Armazena custo com pagamentos, outros custos, quantidade total de tecnicos e horas uteis por dia.';

alter table public.support_monthly_costs enable row level security;

drop policy if exists support_monthly_costs_select on public.support_monthly_costs;
create policy support_monthly_costs_select on public.support_monthly_costs
for select to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_monthly_costs_insert on public.support_monthly_costs;
create policy support_monthly_costs_insert on public.support_monthly_costs
for insert to authenticated
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_monthly_costs_update on public.support_monthly_costs;
create policy support_monthly_costs_update on public.support_monthly_costs
for update to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
)
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_monthly_costs_delete on public.support_monthly_costs;
create policy support_monthly_costs_delete on public.support_monthly_costs
for delete to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

grant select, insert, update, delete on public.support_monthly_costs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
begin
  if to_regclass('public.support_technician_hourly_costs') is not null then
    comment on table public.support_technician_hourly_costs is
    'LEGADO V2.28.0: base individual de custo-hora por tecnico. Mantida por compatibilidade, mas a tela Custos da V2.28.1 nao utiliza esta tabela.';
  end if;
end $$;

commit;
-- <<< MIGRACAO_V2.28.1.sql

-- >>> MIGRACAO_V2.29.0.sql
-- Soften Performance Hub V2.29.0
-- Impacto financeiro da qualidade sem armazenar clientes individualmente.
-- Cada CSV deve vir previamente deduplicado: uma linha valida = um cliente unico na competencia.

begin;

create table if not exists public.quality_financial_monthly (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  active_clients int not null default 0 check (active_clients >= 0),
  avg_ticket numeric(14,2) not null default 0 check (avg_ticket >= 0),
  evaluated_clients int not null default 0 check (evaluated_clients >= 0),
  risk_any_clients int not null default 0 check (risk_any_clients >= 0),
  service_n1 int not null default 0 check (service_n1 >= 0),
  service_n2 int not null default 0 check (service_n2 >= 0),
  service_n3 int not null default 0 check (service_n3 >= 0),
  service_n4 int not null default 0 check (service_n4 >= 0),
  service_n5 int not null default 0 check (service_n5 >= 0),
  product_n1 int not null default 0 check (product_n1 >= 0),
  product_n2 int not null default 0 check (product_n2 >= 0),
  product_n3 int not null default 0 check (product_n3 >= 0),
  product_n4 int not null default 0 check (product_n4 >= 0),
  product_n5 int not null default 0 check (product_n5 >= 0),
  company_n1 int not null default 0 check (company_n1 >= 0),
  company_n2 int not null default 0 check (company_n2 >= 0),
  company_n3 int not null default 0 check (company_n3 >= 0),
  company_n4 int not null default 0 check (company_n4 >= 0),
  company_n5 int not null default 0 check (company_n5 >= 0),
  source_file text null,
  imported_by uuid null references auth.users(id) on delete set null,
  imported_at timestamptz null,
  updated_by uuid null references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint quality_financial_monthly_unique unique (organization_id, year, month),
  constraint quality_financial_risk_le_evaluated check (risk_any_clients <= evaluated_clients)
);

create index if not exists idx_quality_financial_monthly_period
  on public.quality_financial_monthly (organization_id, year, month);

comment on table public.quality_financial_monthly is
'Consolidado mensal do Impacto Financeiro da Qualidade. Nao armazena cliente, nome ou CNPJ. Guarda apenas parametros da carteira e contagens agregadas do CSV previamente deduplicado.';

comment on column public.quality_financial_monthly.risk_any_clients is
'Clientes unicos com pelo menos uma nota de 1 a 3 em Servico, Produto ou Empresa; cada cliente conta no maximo uma vez neste campo.';

alter table public.quality_financial_monthly enable row level security;

drop policy if exists quality_financial_monthly_select on public.quality_financial_monthly;
create policy quality_financial_monthly_select on public.quality_financial_monthly
for select to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists quality_financial_monthly_insert on public.quality_financial_monthly;
create policy quality_financial_monthly_insert on public.quality_financial_monthly
for insert to authenticated
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists quality_financial_monthly_update on public.quality_financial_monthly;
create policy quality_financial_monthly_update on public.quality_financial_monthly
for update to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
)
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists quality_financial_monthly_delete on public.quality_financial_monthly;
create policy quality_financial_monthly_delete on public.quality_financial_monthly
for delete to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

grant select, insert, update, delete on public.quality_financial_monthly to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
-- <<< MIGRACAO_V2.29.0.sql

-- >>> MIGRACAO_V2.29.2.sql
-- Soften Performance Hub V2.29.2
-- Consistencia das referencias/status quando um tecnico e desconsiderado
-- da quantidade do grupo. Nao altera estrutura de tabelas.

begin;

drop function if exists public.get_my_squad_game_ranking(date,date);

create function public.get_my_squad_game_ranking(
  p_start_date date,
  p_end_date date
)
returns table (
  technician_name text,
  att bigint,
  notes5 bigint,
  notes4 bigint,
  notes3 bigint,
  notes2 bigint,
  notes1 bigint,
  total_eval bigint,
  avg_rating numeric,
  eval_pct numeric,
  points numeric,
  goals_hit integer,
  status text,
  ranking bigint,
  exclude_from_group_count boolean
)
language sql
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id, p.squad_id, p.role
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
    limit 1
  ), base as (
    select
      tm.technician_name::text as technician_name,
      coalesce(sum(dm.att),0)::bigint as att,
      coalesce(sum(dm.notes5),0)::bigint as notes5,
      coalesce(sum(dm.notes4),0)::bigint as notes4,
      coalesce(sum(dm.notes3),0)::bigint as notes3,
      coalesce(sum(dm.notes2),0)::bigint as notes2,
      coalesce(sum(dm.notes1),0)::bigint as notes1,
      bool_and(coalesce(tfm.exclude_from_group_count,false)) as exclude_from_group_count
    from me
    join public.squad_months sm on sm.squad_id = me.squad_id
    join public.technician_monthly tm on tm.squad_month_id = sm.id
    join public.daily_metrics dm on dm.technician_month_id = tm.id
    left join public.technician_finance_monthly tfm on tfm.technician_month_id = tm.id
    where me.squad_id is not null
      and me.role in ('technician','squad_admin')
      and make_date(sm.year,sm.month,dm.day) between least(p_start_date,p_end_date) and greatest(p_start_date,p_end_date)
      and dm.day <= coalesce(sm.latest_day,dm.day)
    group by tm.technician_name
  ), metrics as (
    select
      b.*,
      (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::bigint as total_eval,
      case when (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)=0 then 0::numeric
        else trunc(((b.notes5*5+b.notes4*4+b.notes3*3+b.notes2*2+b.notes1)::numeric/(b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::numeric),2)
      end as avg_rating,
      case when b.att=0 then 0::numeric
        else round(((b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::numeric/b.att::numeric),4)
      end as eval_pct
    from base b
    where b.att>0 or (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)>0
  ), population as (
    select
      count(*)::numeric as active_count,
      count(*) filter (where not exclude_from_group_count)::numeric as counted_count,
      sum(att)::numeric as total_att,
      sum(total_eval)::numeric as total_eval
    from metrics
  ), refs as (
    select
      round(p.total_att / greatest(case when p.counted_count>0 then p.counted_count else p.active_count end,1),0) as ref_att,
      round(p.total_eval / greatest(case when p.counted_count>0 then p.counted_count else p.active_count end,1),0) as ref_total_eval,
      coalesce(
        trunc(avg(m.avg_rating) filter (where not m.exclude_from_group_count),2),
        trunc(avg(m.avg_rating),2),
        0::numeric
      ) as ref_avg,
      coalesce(
        round(avg(m.eval_pct) filter (where not m.exclude_from_group_count),4),
        round(avg(m.eval_pct),4),
        0::numeric
      ) as ref_eval_pct
    from metrics m cross join population p
    group by p.total_att,p.total_eval,p.counted_count,p.active_count
  ), scored as (
    select
      m.*,
      ((case when m.att>=r.ref_att then 1 else 0 end)+
       (case when m.total_eval>=r.ref_total_eval then 1 else 0 end)+
       (case when m.avg_rating>=r.ref_avg then 1 else 0 end)+
       (case when m.eval_pct>=r.ref_eval_pct then 1 else 0 end))::integer as goals_hit,
      round(
        m.att::numeric*m.avg_rating
        + case when m.att>=r.ref_att then 20 else -20 end
        + case when m.total_eval>=r.ref_total_eval then 30 else -30 end
        + case when m.avg_rating>=r.ref_avg then 40 else -40 end
        + case when m.eval_pct>=r.ref_eval_pct then 35 else -35 end
      ,2) as points
    from metrics m cross join refs r
  ), ranked as (
    select s.*, row_number() over(order by s.points desc, s.att desc, s.technician_name asc) as ranking
    from scored s
  )
  select
    r.technician_name,r.att,r.notes5,r.notes4,r.notes3,r.notes2,r.notes1,r.total_eval,
    r.avg_rating,r.eval_pct,r.points,r.goals_hit,
    case when r.goals_hit>=2 then 'ACIMA' else 'ABAIXO' end::text as status,
    r.ranking,
    r.exclude_from_group_count
  from ranked r
  order by r.ranking;
$$;

revoke all on function public.get_my_squad_game_ranking(date,date) from public;
grant execute on function public.get_my_squad_game_ranking(date,date) to authenticated;

commit;
-- <<< MIGRACAO_V2.29.2.sql

-- >>> MIGRACAO_V2.29.5.sql
-- Soften Performance Hub V2.29.5
-- Atendimentos nao elegiveis a avaliacao.
-- Mantem a producao integral e retira somente atendimentos sem envio de e-mail
-- dos denominadores de % de avaliacao e % de Notas 5.

begin;

alter table if exists public.technician_monthly
  add column if not exists evaluation_excluded_att numeric(12,2) not null default 0;

comment on column public.technician_monthly.evaluation_excluded_att is
  'Atendimentos da competencia que nao disparam e-mail de avaliacao. Permanecem na producao e sao retirados apenas dos denominadores das taxas de avaliacao/Notas 5.';

-- Consolidado mensal por Squad: taxa usa a base elegivel da competencia.
create or replace function public.get_org_squad_monthly_overview()
returns table (
  squad_code text,
  squad_name text,
  year integer,
  month integer,
  total_att bigint,
  total_eval bigint,
  eval_pct numeric,
  technician_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id
    from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
    limit 1
  )
  select
    s.code::text as squad_code,
    s.name::text as squad_name,
    sm.year,
    sm.month,
    coalesce(sum(tm.att), 0)::bigint as total_att,
    coalesce(sum(tm.total_eval), 0)::bigint as total_eval,
    case
      when coalesce(sum(greatest(tm.att - coalesce(tm.evaluation_excluded_att,0),0)),0) > 0
        then coalesce(sum(tm.total_eval),0)::numeric
             / sum(greatest(tm.att - coalesce(tm.evaluation_excluded_att,0),0))::numeric
      else 0::numeric
    end as eval_pct,
    count(tm.id)::bigint as technician_count
  from me
  join public.squads s
    on s.organization_id = me.organization_id
   and s.active = true
  join public.squad_months sm
    on sm.squad_id = s.id
  left join public.technician_monthly tm
    on tm.squad_month_id = sm.id
  group by s.code, s.name, sm.year, sm.month
  order by sm.year, sm.month, s.code;
$$;

revoke all on function public.get_org_squad_monthly_overview() from public;
grant execute on function public.get_org_squad_monthly_overview() to authenticated;

-- Ranking do tecnico: o ajuste e mensal, portanto e aplicado somente para
-- competencias inteiras contidas no intervalo. Recortes parciais continuam brutos.
drop function if exists public.get_my_squad_game_ranking(date,date);

create function public.get_my_squad_game_ranking(
  p_start_date date,
  p_end_date date
)
returns table (
  technician_name text,
  att bigint,
  notes5 bigint,
  notes4 bigint,
  notes3 bigint,
  notes2 bigint,
  notes1 bigint,
  total_eval bigint,
  avg_rating numeric,
  eval_pct numeric,
  points numeric,
  goals_hit integer,
  status text,
  ranking bigint,
  exclude_from_group_count boolean
)
language sql
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id, p.squad_id, p.role
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
    limit 1
  ), bounds as (
    select least(p_start_date,p_end_date) as date_from,
           greatest(p_start_date,p_end_date) as date_to
  ), base as (
    select
      tm.technician_name::text as technician_name,
      coalesce(sum(dm.att),0)::bigint as att,
      coalesce(sum(dm.notes5),0)::bigint as notes5,
      coalesce(sum(dm.notes4),0)::bigint as notes4,
      coalesce(sum(dm.notes3),0)::bigint as notes3,
      coalesce(sum(dm.notes2),0)::bigint as notes2,
      coalesce(sum(dm.notes1),0)::bigint as notes1,
      bool_and(coalesce(tfm.exclude_from_group_count,false)) as exclude_from_group_count
    from me
    join bounds b on true
    join public.squad_months sm on sm.squad_id = me.squad_id
    join public.technician_monthly tm on tm.squad_month_id = sm.id
    join public.daily_metrics dm on dm.technician_month_id = tm.id
    left join public.technician_finance_monthly tfm on tfm.technician_month_id = tm.id
    where me.squad_id is not null
      and me.role in ('technician','squad_admin')
      and make_date(sm.year,sm.month,dm.day) between b.date_from and b.date_to
      and dm.day <= coalesce(sm.latest_day,dm.day)
    group by tm.technician_name
  ), monthly_excluded as (
    select
      tm.technician_name::text as technician_name,
      coalesce(sum(
        case
          when b.date_from <= make_date(sm.year,sm.month,1)
           and b.date_to >= make_date(sm.year,sm.month,least(
             coalesce(sm.latest_day, extract(day from (date_trunc('month',make_date(sm.year,sm.month,1)) + interval '1 month - 1 day'))::int),
             extract(day from (date_trunc('month',make_date(sm.year,sm.month,1)) + interval '1 month - 1 day'))::int
           ))
          then greatest(coalesce(tm.evaluation_excluded_att,0),0)
          else 0
        end
      ),0)::numeric as evaluation_excluded_att
    from me
    join bounds b on true
    join public.squad_months sm on sm.squad_id = me.squad_id
    join public.technician_monthly tm on tm.squad_month_id = sm.id
    where me.squad_id is not null
      and me.role in ('technician','squad_admin')
      and make_date(sm.year,sm.month,1) <= b.date_to
      and make_date(sm.year,sm.month,least(
            coalesce(sm.latest_day, extract(day from (date_trunc('month',make_date(sm.year,sm.month,1)) + interval '1 month - 1 day'))::int),
            extract(day from (date_trunc('month',make_date(sm.year,sm.month,1)) + interval '1 month - 1 day'))::int
          )) >= b.date_from
    group by tm.technician_name
  ), metrics as (
    select
      b.*,
      (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::bigint as total_eval,
      case when (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)=0 then 0::numeric
        else trunc(((b.notes5*5+b.notes4*4+b.notes3*3+b.notes2*2+b.notes1)::numeric/(b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::numeric),2)
      end as avg_rating,
      greatest(b.att::numeric - coalesce(e.evaluation_excluded_att,0),0) as eligible_att,
      case when greatest(b.att::numeric - coalesce(e.evaluation_excluded_att,0),0)=0 then 0::numeric
        else round(((b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::numeric
          / greatest(b.att::numeric - coalesce(e.evaluation_excluded_att,0),0)),4)
      end as eval_pct
    from base b
    left join monthly_excluded e on e.technician_name = b.technician_name
    where b.att>0 or (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)>0
  ), population as (
    select
      count(*)::numeric as active_count,
      count(*) filter (where not exclude_from_group_count)::numeric as counted_count,
      sum(att)::numeric as total_att,
      sum(total_eval)::numeric as total_eval
    from metrics
  ), refs as (
    select
      round(p.total_att / greatest(case when p.counted_count>0 then p.counted_count else p.active_count end,1),0) as ref_att,
      round(p.total_eval / greatest(case when p.counted_count>0 then p.counted_count else p.active_count end,1),0) as ref_total_eval,
      coalesce(
        trunc(avg(m.avg_rating) filter (where not m.exclude_from_group_count),2),
        trunc(avg(m.avg_rating),2),
        0::numeric
      ) as ref_avg,
      coalesce(
        round(avg(m.eval_pct) filter (where not m.exclude_from_group_count),4),
        round(avg(m.eval_pct),4),
        0::numeric
      ) as ref_eval_pct
    from metrics m cross join population p
    group by p.total_att,p.total_eval,p.counted_count,p.active_count
  ), scored as (
    select
      m.*,
      ((case when m.att>=r.ref_att then 1 else 0 end)+
       (case when m.total_eval>=r.ref_total_eval then 1 else 0 end)+
       (case when m.avg_rating>=r.ref_avg then 1 else 0 end)+
       (case when m.eval_pct>=r.ref_eval_pct then 1 else 0 end))::integer as goals_hit,
      round(
        m.att::numeric*m.avg_rating
        + case when m.att>=r.ref_att then 20 else -20 end
        + case when m.total_eval>=r.ref_total_eval then 30 else -30 end
        + case when m.avg_rating>=r.ref_avg then 40 else -40 end
        + case when m.eval_pct>=r.ref_eval_pct then 35 else -35 end
      ,2) as points
    from metrics m cross join refs r
  ), ranked as (
    select s.*, row_number() over(order by s.points desc, s.att desc, s.technician_name asc) as ranking
    from scored s
  )
  select
    r.technician_name,r.att,r.notes5,r.notes4,r.notes3,r.notes2,r.notes1,r.total_eval,
    r.avg_rating,r.eval_pct,r.points,r.goals_hit,
    case when r.goals_hit>=2 then 'ACIMA' else 'ABAIXO' end::text as status,
    r.ranking,
    r.exclude_from_group_count
  from ranked r
  order by r.ranking;
$$;

revoke all on function public.get_my_squad_game_ranking(date,date) from public;
grant execute on function public.get_my_squad_game_ranking(date,date) to authenticated;

commit;
-- <<< MIGRACAO_V2.29.5.sql

-- >>> MIGRACAO_V2.29.6.sql
-- Soften Performance Hub V2.29.6
-- Consolidação de status operacional x bonificação.
-- 1) O status usa todos os técnicos com produção (2 de 4 = ACIMA).
-- 2) "Desconsiderar na quantidade do Squad" passa a ser exclusivamente financeiro.
-- 3) A RPC do ranking do próprio técnico usa a base elegível de avaliação em competências completas.
-- Não altera estrutura de tabelas.

begin;

drop function if exists public.get_my_squad_game_ranking(date,date);

create function public.get_my_squad_game_ranking(
  p_start_date date,
  p_end_date date
)
returns table (
  technician_name text,
  att bigint,
  notes5 bigint,
  notes4 bigint,
  notes3 bigint,
  notes2 bigint,
  notes1 bigint,
  total_eval bigint,
  avg_rating numeric,
  eval_pct numeric,
  points numeric,
  goals_hit integer,
  status text,
  ranking bigint,
  exclude_from_group_count boolean
)
language sql
security definer
set search_path = public
as $$
  with me as (
    select p.organization_id, p.squad_id, p.role
    from public.profiles p
    where p.user_id = auth.uid()
      and coalesce(p.active,true) = true
    limit 1
  ), bounds as (
    select least(p_start_date,p_end_date) as dt_start,
           greatest(p_start_date,p_end_date) as dt_end
  ), month_segments as (
    select
      tm.technician_name::text as technician_name,
      sm.id as squad_month_id,
      make_date(sm.year,sm.month,1) as month_start,
      make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1))) as month_end,
      case
        when b.dt_start <= make_date(sm.year,sm.month,1)
         and b.dt_end >= make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1)))
        then coalesce(tm.att,0)::bigint
        else coalesce(sum(dm.att),0)::bigint
      end as att,
      case
        when b.dt_start <= make_date(sm.year,sm.month,1)
         and b.dt_end >= make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1)))
        then coalesce(tm.notes5,0)::bigint
        else coalesce(sum(dm.notes5),0)::bigint
      end as notes5,
      case
        when b.dt_start <= make_date(sm.year,sm.month,1)
         and b.dt_end >= make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1)))
        then coalesce(tm.notes4,0)::bigint
        else coalesce(sum(dm.notes4),0)::bigint
      end as notes4,
      case
        when b.dt_start <= make_date(sm.year,sm.month,1)
         and b.dt_end >= make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1)))
        then coalesce(tm.notes3,0)::bigint
        else coalesce(sum(dm.notes3),0)::bigint
      end as notes3,
      case
        when b.dt_start <= make_date(sm.year,sm.month,1)
         and b.dt_end >= make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1)))
        then coalesce(tm.notes2,0)::bigint
        else coalesce(sum(dm.notes2),0)::bigint
      end as notes2,
      case
        when b.dt_start <= make_date(sm.year,sm.month,1)
         and b.dt_end >= make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1)))
        then coalesce(tm.notes1,0)::bigint
        else coalesce(sum(dm.notes1),0)::bigint
      end as notes1,
      case
        when b.dt_start <= make_date(sm.year,sm.month,1)
         and b.dt_end >= make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1)))
        then greatest(0,coalesce(tm.evaluation_excluded_att,0))::bigint
        else 0::bigint
      end as evaluation_excluded_att,
      coalesce(tfm.exclude_from_group_count,false) as exclude_from_group_count
    from me
    cross join bounds b
    join public.squad_months sm on sm.squad_id = me.squad_id
    join public.technician_monthly tm on tm.squad_month_id = sm.id
    left join public.technician_finance_monthly tfm on tfm.technician_month_id = tm.id
    left join public.daily_metrics dm
      on dm.technician_month_id = tm.id
     and dm.day <= coalesce(sm.latest_day,dm.day)
     and make_date(sm.year,sm.month,dm.day) between b.dt_start and b.dt_end
    where me.squad_id is not null
      and me.role in ('technician','squad_admin')
      and make_date(sm.year,sm.month,1) <= b.dt_end
      and make_date(sm.year,sm.month,greatest(1,coalesce(sm.latest_day,1))) >= b.dt_start
    group by tm.id,tm.technician_name,tm.att,tm.notes5,tm.notes4,tm.notes3,tm.notes2,tm.notes1,
             tm.evaluation_excluded_att,tfm.exclude_from_group_count,sm.id,sm.year,sm.month,sm.latest_day,
             b.dt_start,b.dt_end
  ), base as (
    select
      ms.technician_name,
      coalesce(sum(ms.att),0)::bigint as att,
      coalesce(sum(ms.notes5),0)::bigint as notes5,
      coalesce(sum(ms.notes4),0)::bigint as notes4,
      coalesce(sum(ms.notes3),0)::bigint as notes3,
      coalesce(sum(ms.notes2),0)::bigint as notes2,
      coalesce(sum(ms.notes1),0)::bigint as notes1,
      coalesce(sum(ms.evaluation_excluded_att),0)::bigint as evaluation_excluded_att,
      bool_and(ms.exclude_from_group_count) as exclude_from_group_count
    from month_segments ms
    group by ms.technician_name
  ), metrics_pre as (
    select
      b.*,
      (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::bigint as total_eval,
      case when (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)=0 then 0::numeric
        else trunc(((b.notes5*5+b.notes4*4+b.notes3*3+b.notes2*2+b.notes1)::numeric/
          (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)::numeric),2)
      end as avg_rating
    from base b
    where b.att>0 or (b.notes5+b.notes4+b.notes3+b.notes2+b.notes1)>0
  ), metrics as (
    select
      mp.*,
      greatest(
        0,
        mp.att - least(
          greatest(0,mp.evaluation_excluded_att),
          greatest(0,mp.att-mp.total_eval)
        )
      )::bigint as eligible_att,
      case
        when greatest(0,mp.att-least(greatest(0,mp.evaluation_excluded_att),greatest(0,mp.att-mp.total_eval)))=0 then 0::numeric
        else round(
          mp.total_eval::numeric /
          greatest(0,mp.att-least(greatest(0,mp.evaluation_excluded_att),greatest(0,mp.att-mp.total_eval)))::numeric,
          4
        )
      end as eval_pct
    from metrics_pre mp
  ), refs as (
    select
      coalesce(round(avg(m.att::numeric),0),0::numeric) as ref_att,
      coalesce(round(avg(m.total_eval::numeric),0),0::numeric) as ref_total_eval,
      coalesce(trunc(avg(m.avg_rating),2),0::numeric) as ref_avg,
      coalesce(round(avg(m.eval_pct),4),0::numeric) as ref_eval_pct
    from metrics m
  ), scored as (
    select
      m.*,
      ((case when m.att>=r.ref_att then 1 else 0 end)+
       (case when m.total_eval>=r.ref_total_eval then 1 else 0 end)+
       (case when m.avg_rating>=r.ref_avg then 1 else 0 end)+
       (case when m.eval_pct>=r.ref_eval_pct then 1 else 0 end))::integer as goals_hit,
      round(
        m.att::numeric*m.avg_rating
        + case when m.att>=r.ref_att then 20 else -20 end
        + case when m.total_eval>=r.ref_total_eval then 30 else -30 end
        + case when m.avg_rating>=r.ref_avg then 40 else -40 end
        + case when m.eval_pct>=r.ref_eval_pct then 35 else -35 end,
        2
      ) as points
    from metrics m cross join refs r
  ), ranked as (
    select s.*, row_number() over(order by s.points desc, s.att desc, s.technician_name asc) as ranking
    from scored s
  )
  select
    r.technician_name,r.att,r.notes5,r.notes4,r.notes3,r.notes2,r.notes1,r.total_eval,
    r.avg_rating,r.eval_pct,r.points,r.goals_hit,
    case when r.goals_hit>=2 then 'ACIMA' else 'ABAIXO' end::text as status,
    r.ranking,
    r.exclude_from_group_count
  from ranked r
  order by r.ranking;
$$;

revoke all on function public.get_my_squad_game_ranking(date,date) from public;
grant execute on function public.get_my_squad_game_ranking(date,date) to authenticated;

commit;
-- <<< MIGRACAO_V2.29.6.sql

-- Fim das evoluções cumulativas até V2.29.6.


-- >>> MIGRACAO_V2.29.8.sql
-- SOFTEN PERFORMANCE HUB V2.29.8
-- Auditoria administrativa imutável e rastreabilidade das operações críticas.
-- Execute uma única vez no SQL Editor do Supabase antes de usar a tela Auditoria.

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  squad_id uuid references public.squads(id) on delete set null,
  actor_user_id uuid,
  actor_name text not null,
  actor_email text,
  actor_role text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  description text,
  before_data jsonb not null default '{}'::jsonb,
  after_data jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_org_created on public.audit_logs(organization_id, created_at desc);
create index if not exists idx_audit_logs_squad_created on public.audit_logs(squad_id, created_at desc);
create index if not exists idx_audit_logs_action on public.audit_logs(action);
create index if not exists idx_audit_logs_actor on public.audit_logs(actor_user_id, created_at desc);

alter table public.audit_logs enable row level security;

drop policy if exists audit_logs_select on public.audit_logs;
create policy audit_logs_select on public.audit_logs
for select to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.organization_id = audit_logs.organization_id
      and (
        p.role = 'super_admin'
        or (p.role = 'squad_admin' and audit_logs.squad_id = p.squad_id)
      )
  )
);

-- Não existe policy de INSERT/UPDATE/DELETE para o cliente.
-- Toda inclusão passa pela função abaixo, que deriva o ator da sessão autenticada.
revoke insert, update, delete on public.audit_logs from anon, authenticated;
grant select on public.audit_logs to authenticated;

create or replace function public.log_audit_event(
  p_action text,
  p_entity_type text,
  p_entity_id text default null,
  p_squad_id uuid default null,
  p_description text default null,
  p_before_data jsonb default '{}'::jsonb,
  p_after_data jsonb default '{}'::jsonb,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  actor public.profiles%rowtype;
  result_id uuid;
begin
  select p.* into actor
  from public.profiles p
  where p.user_id = auth.uid()
    and p.active = true
  limit 1;

  if actor.user_id is null or actor.role not in ('super_admin','squad_admin') then
    raise exception 'Sem permissão para registrar auditoria.' using errcode = '42501';
  end if;

  if coalesce(trim(p_action),'') = '' or coalesce(trim(p_entity_type),'') = '' then
    raise exception 'Ação e tipo da entidade são obrigatórios.' using errcode = '22023';
  end if;

  if actor.role = 'squad_admin' then
    if p_squad_id is null or p_squad_id <> actor.squad_id then
      raise exception 'Admin do Squad só pode auditar ações do próprio Squad.' using errcode = '42501';
    end if;
  elsif p_squad_id is not null and not exists (
    select 1 from public.squads s
    where s.id = p_squad_id and s.organization_id = actor.organization_id
  ) then
    raise exception 'Squad fora da organização do usuário.' using errcode = '42501';
  end if;

  insert into public.audit_logs (
    organization_id,squad_id,actor_user_id,actor_name,actor_email,actor_role,
    action,entity_type,entity_id,description,before_data,after_data,metadata
  ) values (
    actor.organization_id,p_squad_id,actor.user_id,actor.full_name,actor.email,actor.role,
    trim(p_action),trim(p_entity_type),nullif(trim(coalesce(p_entity_id,'')),''),
    nullif(trim(coalesce(p_description,'')),''),
    coalesce(p_before_data,'{}'::jsonb),coalesce(p_after_data,'{}'::jsonb),coalesce(p_metadata,'{}'::jsonb)
  ) returning id into result_id;

  return result_id;
end;
$$;

revoke all on function public.log_audit_event(text,text,text,uuid,text,jsonb,jsonb,jsonb) from public;
grant execute on function public.log_audit_event(text,text,text,uuid,text,jsonb,jsonb,jsonb) to authenticated;
-- <<< MIGRACAO_V2.29.8.sql

-- >>> MIGRACAO_V2.29.9.sql
-- SOFTEN PERFORMANCE HUB V2.29.9
-- Compatibilidade com a mudança de exposição da Data API do Supabase em 30/10/2026.
-- Torna explícitos os GRANTs que o projeto realmente utiliza e deixa de depender
-- dos privilégios automáticos para novas tabelas no schema public.
-- Pode ser executada com segurança em uma base existente: GRANT é idempotente.

begin;

-- Data API usada pelo frontend autenticado.
-- Estas tabelas foram criadas na V2.18.0 sem GRANT explícito.
grant select, insert, update, delete
on table public.technician_finance_monthly
  to authenticated;

grant select, insert, update
on table public.super_admin_commissions
  to authenticated;

-- Data API usada pelas Edge Functions create-user e manage-user.
-- O service_role ignora RLS, mas continua precisando de privilégio SQL na tabela.
grant usage on schema public to service_role;

grant select, insert, update
on table public.profiles
  to service_role;

grant select
on table public.squads
  to service_role;

grant select
on table public.squad_months
  to service_role;

grant select, update
on table public.technician_monthly
  to service_role;

grant select, insert, update
on table public.profile_squad_history
  to service_role;

grant insert
on table public.audit_logs
  to service_role;

-- Não é concedido acesso ao role anon. O dashboard exige autenticação antes
-- de consultar dados da aplicação.

commit;
-- <<< MIGRACAO_V2.29.9.sql

-- Fim do instalador cumulativo V2.29.9.
