-- Soften Performance Hub V2.48.7
-- Calendario operacional compartilhado pela organizacao para calculos financeiros por dias uteis.

begin;

create table if not exists public.business_calendar_exceptions (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  date date not null,
  description text not null check (length(btrim(description)) between 1 and 120),
  type text not null default 'company' check (type in ('national','state','municipal','company')),
  active boolean not null default true,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  updated_by uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_calendar_exceptions_unique unique (organization_id, date)
);

create index if not exists idx_business_calendar_exceptions_org_date
  on public.business_calendar_exceptions (organization_id, date);

comment on table public.business_calendar_exceptions is
'Dias nao uteis adicionais usados pelo calendario operacional da organizacao. A aplicacao combina estes registros com os feriados nacionais fixos padrao e congela a memoria no fechamento da competencia.';

alter table public.business_calendar_exceptions enable row level security;

drop policy if exists business_calendar_exceptions_select on public.business_calendar_exceptions;
create policy business_calendar_exceptions_select on public.business_calendar_exceptions
for select to authenticated
using (
  organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists business_calendar_exceptions_insert on public.business_calendar_exceptions;
create policy business_calendar_exceptions_insert on public.business_calendar_exceptions
for insert to authenticated
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists business_calendar_exceptions_update on public.business_calendar_exceptions;
create policy business_calendar_exceptions_update on public.business_calendar_exceptions
for update to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
)
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists business_calendar_exceptions_delete on public.business_calendar_exceptions;
create policy business_calendar_exceptions_delete on public.business_calendar_exceptions
for delete to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

grant select, insert, update, delete on public.business_calendar_exceptions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
